apiVersion: 1
datasources:
- access: proxy
  editable: true
  isDefault: true
  name: Prometheus
  type: prometheus
  url: http://prometheus:9090

- access: proxy
  database: foreman
  editable: true
  isDefault: false
  jsonData:
    postgresVersion: $PSQL_VERSION
    sslmode: disable
    timescaledb: true
  name: foreman
  password: $PGSQL_FOREMAN_PASSWORD
  type: postgres
  url: $PGSQL_FOREMAN_HOST:$PGSQL_FOREMAN_PORT
  user: $PGSQL_FOREMAN_USER

- access: proxy
  database: candlepin
  editable: true
  isDefault: false
  jsonData:
    postgresVersion: $PGSQL_VERSION
    sslmode: disable
    timescaledb: true
  name: candlepin
  password: $PGSQL_CANDLEPIN_PASSWORD
  type: postgres
  url: $PGSQL_CANDLEPIN_HOST:$PGSQL_CANDLEPIN_PORT
  user: $PGSQL_CANDLEPIN_USER
