apiVersion: 1
datasources:
- access: proxy
  editable: true
  isDefault: true
  name: Prometheus
  type: prometheus
  url: http://mrsdalloway:9090

- access: proxy
  database: foreman
  editable: true
  isDefault: false
  jsonData:
    postgresVersion: 9.5
    sslmode: disable
    timescaledb: true
  name: foreman
  password: $PGSQL_FOREMAN_PASSWORD
  type: postgres
  url: $PGSQL_FOREMAN_HOST:$PGSQL_FOREMAN_PORT
  user: $PGSQL_FOREMAN_USER
